from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

gen_schematic = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'USB_C_Receptacle', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_Receptacle'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_USB:USB_C_Receptacle_GCT_USB4125-xx-x_6P_TopMnt_Horizontal', 'keywords':'usb universal serial bus type-C full-featured', 'description':'USB Full-Featured Type-C Receptacle connector', 'datasheet':'https://www.usb.org/sites/default/files/documents/usb_type-c.zip', 'pins':[
            Pin(num='S1',name='SHIELD',func=pin_types.PASSIVE,unit=1),
            Pin(num='A1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='A7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='B7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='A6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='B6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='B10',name='RX1-',func=pin_types.BIDIR,unit=1),
            Pin(num='B11',name='RX1+',func=pin_types.BIDIR,unit=1),
            Pin(num='A3',name='TX1-',func=pin_types.BIDIR,unit=1),
            Pin(num='A2',name='TX1+',func=pin_types.BIDIR,unit=1),
            Pin(num='A10',name='RX2-',func=pin_types.BIDIR,unit=1),
            Pin(num='A11',name='RX2+',func=pin_types.BIDIR,unit=1),
            Pin(num='B3',name='TX2-',func=pin_types.BIDIR,unit=1),
            Pin(num='B2',name='TX2+',func=pin_types.BIDIR,unit=1),
            Pin(num='A8',name='SBU1',func=pin_types.BIDIR,unit=1),
            Pin(num='B8',name='SBU2',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TP4056-42-ESOP8', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TP4056-42-ESOP8'}), 'ref_prefix':'U', 'fplist':['Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias'], 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'keywords':'lithium-ion lithium-polymer Li-Poly', 'description':'1A Standalone Linear Li-ion/LiPo single-cell battery charger, 4.2V Â±1% charge voltage, VCC = 4.0..8.0V, SOIC-8 (SOP-8)', 'datasheet':'https://www.lcsc.com/datasheet/lcsc_datasheet_2410121619_TOPPOWER-Nanjing-Extension-Microelectronics-TP4056-42-ESOP8_C16581.pdf', 'pins':[
            Pin(num='8',name='CE',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='~{CHRG}',func=pin_types.OPENCOLL,unit=1),
            Pin(num='6',name='~{STDBY}',func=pin_types.OPENCOLL,unit=1),
            Pin(num='9',name='EPAD',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='V_{CC}',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='BAT',func=pin_types.PWROUT,unit=1),
            Pin(num='1',name='TEMP',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='PROG',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0402_1005Metric', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_JST:JST_PH_B2B-PH-K_1x02_P2.00mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x02, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MT3608', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MT3608'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-6'], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'Step-Up Boost DC-DC Regulator Adjustable', 'description':'High Efficiency 1.2MHz 2A Step Up Converter, 2-24V Vin, 28V Vout, 4A current limit, 1.2MHz, SOT23-6', 'datasheet':'https://www.olimex.com/Products/Breadboarding/BB-PWR-3608/resources/MT3608.pdf', 'pins':[
            Pin(num='5',name='IN',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='6',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='1',name='SW',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='FB',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'Inductor_SMD:L_0805_2012Metric', 'keywords':'inductor choke coil reactor magnetic', 'description':'Inductor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D_Schottky', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SOD-123', 'keywords':'diode Schottky', 'description':'Schottky diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AMS1117-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AMS1117-3.3'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'Package_TO_SOT_SMD:SOT-223-3_TabPin2'], 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':'linear regulator ldo fixed positive', 'description':'1A Low Dropout regulator, positive, 3.3V fixed output, SOT-223', 'datasheet':'http://www.advanced-monolithic.com/pdf/ds1117.pdf', 'pins':[
            Pin(num='3',name='VI',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VO',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'RP2354A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RP2354A'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:QFN-60-1EP_7x7mm_P0.4mm_EP3.4x3.4mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='2',name='GPIO0',func=pin_types.BIDIR),
            Pin(num='3',name='GPIO1',func=pin_types.BIDIR),
            Pin(num='4',name='GPIO2',func=pin_types.BIDIR),
            Pin(num='5',name='GPIO3',func=pin_types.BIDIR),
            Pin(num='7',name='GPIO4',func=pin_types.BIDIR),
            Pin(num='8',name='GPIO5',func=pin_types.BIDIR),
            Pin(num='9',name='GPIO6',func=pin_types.BIDIR),
            Pin(num='10',name='GPIO7',func=pin_types.BIDIR),
            Pin(num='12',name='GPIO8',func=pin_types.BIDIR),
            Pin(num='13',name='GPIO9',func=pin_types.BIDIR),
            Pin(num='14',name='GPIO10',func=pin_types.BIDIR),
            Pin(num='15',name='GPIO11',func=pin_types.BIDIR),
            Pin(num='16',name='GPIO12',func=pin_types.BIDIR),
            Pin(num='17',name='GPIO13',func=pin_types.BIDIR),
            Pin(num='18',name='GPIO14',func=pin_types.BIDIR),
            Pin(num='19',name='GPIO15',func=pin_types.BIDIR),
            Pin(num='27',name='GPIO16',func=pin_types.BIDIR),
            Pin(num='28',name='GPIO17',func=pin_types.BIDIR),
            Pin(num='29',name='GPIO18',func=pin_types.BIDIR),
            Pin(num='31',name='GPIO19',func=pin_types.BIDIR),
            Pin(num='32',name='GPIO20',func=pin_types.BIDIR),
            Pin(num='33',name='GPIO21',func=pin_types.BIDIR),
            Pin(num='34',name='GPIO22',func=pin_types.BIDIR),
            Pin(num='35',name='GPIO23',func=pin_types.BIDIR),
            Pin(num='36',name='GPIO24',func=pin_types.BIDIR),
            Pin(num='37',name='GPIO25',func=pin_types.BIDIR),
            Pin(num='40',name='GPIO26',func=pin_types.BIDIR),
            Pin(num='41',name='GPIO27',func=pin_types.BIDIR),
            Pin(num='42',name='GPIO28',func=pin_types.BIDIR),
            Pin(num='43',name='GPIO29',func=pin_types.BIDIR),
            Pin(num='21',name='XIN',func=pin_types.INPUT),
            Pin(num='22',name='XOUT',func=pin_types.OUTPUT),
            Pin(num='52',name='USB_DP',func=pin_types.BIDIR),
            Pin(num='51',name='USB_DM',func=pin_types.BIDIR),
            Pin(num='26',name='RUN',func=pin_types.INPUT),
            Pin(num='24',name='SWCLK',func=pin_types.INPUT),
            Pin(num='25',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='60',name='QSPI_SS',func=pin_types.BIDIR),
            Pin(num='56',name='QSPI_SCLK',func=pin_types.BIDIR),
            Pin(num='57',name='QSPI_SD0',func=pin_types.BIDIR),
            Pin(num='59',name='QSPI_SD1',func=pin_types.BIDIR),
            Pin(num='58',name='QSPI_SD2',func=pin_types.BIDIR),
            Pin(num='55',name='QSPI_SD3',func=pin_types.BIDIR),
            Pin(num='1',name='IOVDD1',func=pin_types.PWRIN),
            Pin(num='11',name='IOVDD2',func=pin_types.PWRIN),
            Pin(num='20',name='IOVDD3',func=pin_types.PWRIN),
            Pin(num='30',name='IOVDD4',func=pin_types.PWRIN),
            Pin(num='38',name='IOVDD5',func=pin_types.PWRIN),
            Pin(num='45',name='IOVDD6',func=pin_types.PWRIN),
            Pin(num='53',name='USB_OTP_VDD',func=pin_types.PWRIN),
            Pin(num='54',name='QSPI_IOVDD',func=pin_types.PWRIN),
            Pin(num='44',name='ADC_AVDD',func=pin_types.PWRIN),
            Pin(num='46',name='VREG_AVDD',func=pin_types.PWRIN),
            Pin(num='49',name='VREG_VIN',func=pin_types.PWRIN),
            Pin(num='6',name='DVDD1',func=pin_types.PWRIN),
            Pin(num='23',name='DVDD2',func=pin_types.PWRIN),
            Pin(num='39',name='DVDD3',func=pin_types.PWRIN),
            Pin(num='61',name='GND',func=pin_types.PWRIN),
            Pin(num='47',name='VREG_PGND',func=pin_types.PWRIN),
            Pin(num='48',name='VREG_LX',func=pin_types.PWROUT),
            Pin(num='50',name='VREG_FB',func=pin_types.INPUT)] }),
        Part(**{ 'name':'Crystal', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal'}), 'ref_prefix':'Y', 'fplist':[''], 'footprint':'Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm', 'keywords':'quartz ceramic resonator oscillator', 'description':'Two pin crystal', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':[''], 'footprint':'Button_Switch_SMD:SW_Push_1P1T_NO_CK_KSC7xxJ', 'keywords':'switch normally-open pushbutton push-button', 'description':'Push button switch, generic, two pins', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'W5500', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W5500'}), 'ref_prefix':'U', 'fplist':['Package_QFP:LQFP-48_7x7mm_P0.5mm'], 'footprint':'Package_QFP:LQFP-48_7x7mm_P0.5mm', 'keywords':'WIZnet Ethernet controller', 'description':'10/100Mb SPI Ethernet controller with TCP/IP stack, LQFP-48', 'datasheet':'http://wizwiki.net/wiki/lib/exe/fetch.php/products:w5500:w5500_ds_v109e.pdf', 'pins':[
            Pin(num='32',name='~{SCS}',func=pin_types.INPUT,unit=1),
            Pin(num='33',name='SCLK',func=pin_types.INPUT,unit=1),
            Pin(num='34',name='MISO',func=pin_types.OUTPUT,unit=1),
            Pin(num='35',name='MOSI',func=pin_types.INPUT,unit=1),
            Pin(num='36',name='~{INT}',func=pin_types.INPUT,unit=1),
            Pin(num='37',name='~{RST}',func=pin_types.INPUT,unit=1),
            Pin(num='45',name='PMODE0',func=pin_types.INPUT,unit=1),
            Pin(num='44',name='PMODE1',func=pin_types.INPUT,unit=1),
            Pin(num='43',name='PMODE2',func=pin_types.INPUT,unit=1),
            Pin(num='30',name='XI/CLKIN',func=pin_types.INPUT,unit=1),
            Pin(num='31',name='XO',func=pin_types.OUTPUT,unit=1),
            Pin(num='38',name='RSVD',func=pin_types.INPUT,unit=1),
            Pin(num='39',name='RSVD',func=pin_types.INPUT,unit=1),
            Pin(num='40',name='RSVD',func=pin_types.INPUT,unit=1),
            Pin(num='41',name='RSVD',func=pin_types.INPUT,unit=1),
            Pin(num='42',name='RSVD',func=pin_types.INPUT,unit=1),
            Pin(num='23',name='RSVD',func=pin_types.INPUT,unit=1),
            Pin(num='28',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='29',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='AVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='AVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='AVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='21',name='AVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='AVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='AGND',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='AGND',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='AGND',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='48',name='AGND',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='AGND',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='DNC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='12',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='13',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='46',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='47',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='1',name='TXN',func=pin_types.OUTPUT,unit=1),
            Pin(num='2',name='TXP',func=pin_types.OUTPUT,unit=1),
            Pin(num='5',name='RXN',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='RXP',func=pin_types.INPUT,unit=1),
            Pin(num='24',name='SPDLED',func=pin_types.OUTPUT,unit=1),
            Pin(num='25',name='LINKLED',func=pin_types.OUTPUT,unit=1),
            Pin(num='26',name='DUPLED',func=pin_types.OUTPUT,unit=1),
            Pin(num='27',name='ACTLED',func=pin_types.OUTPUT,unit=1),
            Pin(num='10',name='EXRES1',func=pin_types.PASSIVE,unit=1),
            Pin(num='18',name='VBG',func=pin_types.PASSIVE,unit=1),
            Pin(num='20',name='TOCAP',func=pin_types.PASSIVE,unit=1),
            Pin(num='22',name='1V2O',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'RJ45_Hanrun_HR911105A_Horizontal', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RJ45_Hanrun_HR911105A_Horizontal'}), 'ref_prefix':'J', 'fplist':['Connector_RJ:RJ45_Hanrun_HR911105A_Horizontal'], 'footprint':'Connector_RJ:RJ45_Hanrun_HR911105A_Horizontal', 'keywords':'RJ45 Magjack Socket', 'description':'1 Port RJ45 Magjack Connector Through Hole 10/100 Base-T, AutoMDIX', 'datasheet':'https://datasheet.lcsc.com/lcsc/1811141815_HANRUN-Zhongshan-HanRun-Elec-HR911105A_C12074.pdf', 'pins':[
            Pin(num='1',name='TD+',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='TCT',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='TD-',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='RD+',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='RCT',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='RD-',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',func=pin_types.PWRIN,unit=1),
            Pin(num='SH',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='12',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'74AHCT125', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74AHCT125'}), 'ref_prefix':'U', 'fplist':['', ''], 'footprint':'Package_SO:SOIC-14_3.9x8.7mm_P1.27mm', 'keywords':'buffer 3State', 'description':'Quadruple Bus Buffer Gates With 3-State Outputs', 'datasheet':'https://www.ti.com/lit/ds/symlink/sn74ahct125.pdf', 'pins':[
            Pin(num='2',name='~',func=pin_types.INPUT,unit=1),
            Pin(num='1',name='~',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='~',func=pin_types.TRISTATE,unit=1),
            Pin(num='5',name='~',func=pin_types.INPUT,unit=2),
            Pin(num='4',name='~',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='~',func=pin_types.TRISTATE,unit=2),
            Pin(num='9',name='~',func=pin_types.INPUT,unit=3),
            Pin(num='10',name='~',func=pin_types.INPUT,unit=3),
            Pin(num='8',name='~',func=pin_types.TRISTATE,unit=3),
            Pin(num='12',name='~',func=pin_types.INPUT,unit=4),
            Pin(num='13',name='~',func=pin_types.INPUT,unit=4),
            Pin(num='11',name='~',func=pin_types.TRISTATE,unit=4),
            Pin(num='14',name='VCC',func=pin_types.PWRIN,unit=5),
            Pin(num='7',name='GND',func=pin_types.PWRIN,unit=5)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['2', '1', '3']},{'label': 'uB', 'num': 2, 'pin_nums': ['4', '6', '5']},{'label': 'uC', 'num': 3, 'pin_nums': ['9', '10', '8']},{'label': 'uD', 'num': 4, 'pin_nums': ['12', '11', '13']},{'label': 'uE', 'num': 5, 'pin_nums': ['14', '7']}] }),
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x03, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])