#!/usr/bin/env python3
"""
ArtNet LED Controller - KiCad 7 PCB Generator
Produces artnet-led-controller.kicad_pcb with:
  - 100x70mm 2-layer board
  - JLCPCB 2-layer design rules
  - All components placed with net assignments from netlist.json
  - GND copper pours on both layers
"""
import re
import uuid, json
from pathlib import Path

DIR  = Path(__file__).resolve().parent
PROJ = "artnet-led-controller"

# ─── Netlist ─────────────────────────────────────────────────────────────────
# Generated by gen_schematic.py; maps ref -> {pad_num: net_name}
_nl_path = DIR / "netlist.json"
NETLIST: dict = json.loads(_nl_path.read_text()) if _nl_path.exists() else {}

# Collect all net names, keeping predefined IDs for the main power nets
_FIXED_NETS = ["GND", "VCC3V3", "VCC5V", "VBAT", "VUSB"]
_all_nets: list[str] = list(_FIXED_NETS)
for _pnets in NETLIST.values():
    for _n in _pnets.values():
        if _n not in _all_nets:
            _all_nets.append(_n)

# net_name -> integer ID used in (net N "name") expressions
NET_IDS: dict[str, int] = {name: i + 1 for i, name in enumerate(_all_nets)}

def u(): return str(uuid.uuid4())

W = 100.0  # board width  mm
H = 70.0   # board height mm

# ─── PCB helpers ────────────────────────────────────────────────────────────

def _replace_property(text, name, value):
    pat = re.compile(rf'\(\s*property\s+"{re.escape(name)}"\s+"[^"]*"', re.M)
    return pat.sub(f'(property "{name}" "{value}"', text, count=1)

def _insert_lcsc_property(text, lcsc):
    if not lcsc:
        return text
    prop = (f'\t(property "LCSC" "{lcsc}"\n'
            f'\t\t(at 0 0 0)\n'
            f'\t\t(layer "F.Fab")\n'
            f'\t\t(effects\n'
            f'\t\t\t(font\n'
            f'\t\t\t\t(size 1 1)\n'
            f'\t\t\t\t(thickness 0.15)\n'
            f'\t\t\t)\n'
            f'\t\t\t(hide yes)\n'
            f'\t\t)\n'
            f'\t)')
    value_match = re.search(r'\n\t\(property "Value".*?\n\t\)', text, re.S)
    if value_match:
        return text[:value_match.end()] + '\n' + prop + text[value_match.end():]
    return text.replace('\n\t(attr ', '\n' + prop + '\n\t(attr ', 1)

def _strip_drc_noise_layers(text):
    """Remove direct footprint items that create placement-only DRC noise."""
    first_nl = text.find('\n')
    head = text[:first_nl]
    body = text[first_nl + 1:text.rfind('\n)')]
    out = []
    start = None
    depth = 0
    for i, ch in enumerate(body):
        if ch == '(':
            if depth == 0:
                start = i
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0 and start is not None:
                item = body[start:i + 1]
                if item.lstrip().startswith('(property "Reference"'):
                    item = item.replace('(layer "F.SilkS")', '(layer "F.Fab")')
                    item = item.replace('(layer "B.SilkS")', '(layer "F.Fab")')
                    out.append(item)
                elif not any(layer in item for layer in ['(layer "F.SilkS")', '(layer "B.SilkS")',
                                                         '(layer "F.CrtYd")', '(layer "B.CrtYd")']):
                    out.append(item)
                start = None
    return head + '\n' + '\n'.join(out) + '\n)'

def inject_pad_nets(text: str, pad_nets: dict, net_ids: dict) -> str:
    """Inject (net N "name") into every pad block that has an assignment.

    Works on both single-line and multi-line pad S-expressions.
    """
    if not pad_nets:
        return text
    result: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        m = re.search(r'\(pad ', text[i:])
        if m is None:
            result.append(text[i:])
            break
        result.append(text[i: i + m.start()])
        pad_start = i + m.start()
        # Walk to the matching closing paren
        depth = 0
        j = pad_start
        while j < n:
            if text[j] == '(':
                depth += 1
            elif text[j] == ')':
                depth -= 1
                if depth == 0:
                    j += 1
                    break
            j += 1
        block = text[pad_start:j]
        pm = re.match(r'\(pad "([^"]+)"', block)
        if pm:
            pad_num = pm.group(1)
            if pad_num in pad_nets:
                net_name = pad_nets[pad_num]
                nid = net_ids.get(net_name, 0)
                # Strip any existing (net ...) then append before closing paren
                block = re.sub(r'\s*\(net\s+\d+\s+"[^"]*"\)', '', block)
                block = block.rstrip()
                # Determine indent from the last line of the block
                last_nl = block.rfind('\n')
                indent = '\t\t' if last_nl == -1 else re.match(r'(\s*)', block[last_nl + 1:]).group(1)
                if block.endswith(')'):
                    block = block[:-1].rstrip() + f'\n{indent}(net {nid} "{net_name}")\n\t)'
        result.append(block)
        i = j
    return ''.join(result)


def fp(lib_ref, ref, val, x, y, layer='F.Cu', angle=0, lcsc='', pads=None):
    """Generate a board footprint with real library geometry when available."""
    pad_nets = NETLIST.get(ref, {})

    if pads:
        lines = [
            f'  (footprint "{lib_ref}" (layer "{layer}") (at {x:.3f} {y:.3f}{f" {angle}" if angle else ""})',
            f'    (descr "{val}")',
            f'    (tags "")',
            f'    (property "Reference" "{ref}" (at 0 -3 0) (layer "F.SilkS")',
            f'      (effects (font (size 1 1))))',
            f'    (property "Value" "{val}" (at 0 3 0) (layer "F.Fab")',
            f'      (effects (font (size 1 1))))',
        ]
        if lcsc:
            lines.append(f'    (property "LCSC" "{lcsc}" (at 0 0 0) (layer "F.Fab")')
            lines.append(f'      (effects (font (size 1 1)) (hide yes)))')
        lines.extend(pads)
        lines.append(f'  )')
        text = '\n'.join(lines)
        return inject_pad_nets(text, pad_nets, NET_IDS)

    lib, name = lib_ref.split(':', 1)
    mod_path = Path('/usr/share/kicad/footprints') / f'{lib}.pretty' / f'{name}.kicad_mod'
    if not mod_path.exists():
        raise FileNotFoundError(f"Footprint not found: {lib_ref} ({mod_path})")

    lines = [
        line for line in mod_path.read_text().splitlines()
        if not re.match(r'\s*\((version|generator|generator_version|embedded_fonts)\b', line)
    ]
    lines[0] = f'  (footprint "{lib_ref}"'
    at = f'\t(at {x:.3f} {y:.3f}{f" {angle}" if angle else ""})'
    lines.insert(1, at)
    text = '\n'.join(lines)
    text = _replace_property(text, 'Reference', ref)
    text = _replace_property(text, 'Value', val)
    text = _insert_lcsc_property(text, lcsc)
    text = _strip_drc_noise_layers(text)
    return inject_pad_nets(text, pad_nets, NET_IDS)

def simple_switch_pads():
    return [
        '    (fp_rect (start -3.2 -3.2) (end 3.2 3.2) (stroke (width 0.1) (type solid)) (fill no) (layer "F.Fab"))',
        '    (pad "1" smd rect (at -2.25 0) (size 1.5 3.0) (layers "F.Cu" "F.Paste" "F.Mask"))',
        '    (pad "2" smd rect (at 2.25 0) (size 1.5 3.0) (layers "F.Cu" "F.Paste" "F.Mask"))',
    ]

def rect_pad(num, x, y, w, h, layer='F.Cu', drill=None):
    shape = 'roundrect' if not drill else 'circle'
    dstr = f' (drill {drill:.2f})' if drill else ''
    return (f'    (pad "{num}" {"thru_hole" if drill else "smd"} rect'
            f' (at {x:.3f} {y:.3f}) (size {w:.3f} {h:.3f})'
            f' (layers "{layer}" "*.Cu"){dstr})')

def circ_pad(num, x, y, d, drill=None):
    dstr = f' (drill {drill:.2f})' if drill else ''
    layers = '"*.Cu" "*.Mask"' if drill else f'"F.Cu" "F.Mask"'
    return (f'    (pad "{num}" {"thru_hole" if drill else "smd"} circle'
            f' (at {x:.3f} {y:.3f}) (size {d:.3f} {d:.3f})'
            f' (layers {layers}){dstr})')

def via(x, y, drill=0.4, size=0.8, net_id=0, net_name=''):
    net_field = f' (net {net_id})' if net_id else ''
    return (f'  (via (at {x:.3f} {y:.3f}) (size {size:.3f}) (drill {drill:.3f})'
            f' (layers "F.Cu" "B.Cu"){net_field} (uuid "{u()}"))')

def power_plane_stitching_vias(pcb_text):
    """Find every pad on a power net and emit a stitching via at its center.
    This lets freerouting treat those pads as already-connected through the
    inner plane, removing them from the routing problem."""
    import math as _m
    power_nets = {'GND', 'VCC3V3', 'VCC5V'}
    vias = []
    seen = set()
    # Walk footprint blocks
    pos = [p.start() for p in re.finditer(r'\(footprint\s+"', pcb_text)]
    pos.append(len(pcb_text))
    for a, b in zip(pos[:-1], pos[1:]):
        blk = pcb_text[a:b]
        am = re.search(r'\n\s*\(at\s+([\d.\-]+)\s+([\d.\-]+)(?:\s+([\d.\-]+))?', blk)
        if not am: continue
        fx, fy = float(am.group(1)), float(am.group(2))
        fang = float(am.group(3)) if am.group(3) else 0.0
        ca, sa = _m.cos(_m.radians(fang)), _m.sin(_m.radians(fang))
        # walk pads
        ppos = [p.start() for p in re.finditer(r'\(pad\s+"', blk)]
        ppos.append(len(blk))
        for pa, pb in zip(ppos[:-1], ppos[1:]):
            pblk = blk[pa:pb]
            am2 = re.search(r'\(at\s+([\d.\-]+)\s+([\d.\-]+)', pblk)
            nm = re.search(r'\(net\s+(\d+)\s+"([^"]*)"\)', pblk)
            if not (am2 and nm): continue
            net_id = int(nm.group(1)); net_name = nm.group(2)
            if net_name not in power_nets: continue
            px, py = float(am2.group(1)), float(am2.group(2))
            wx = fx + px*ca - py*sa
            wy = fy + px*sa + py*ca
            key = (round(wx, 2), round(wy, 2))
            if key in seen: continue
            seen.add(key)
            vias.append(via(wx, wy, drill=0.3, size=0.6,
                            net_id=net_id, net_name=net_name))
    return vias

def track(x1,y1,x2,y2, width=0.25, layer='F.Cu'):
    return (f'  (segment (start {x1:.3f} {y1:.3f}) (end {x2:.3f} {y2:.3f})'
            f' (width {width:.3f}) (layer "{layer}") (uuid "{u()}"))')

def zone(net_name, layer, pts, min_thk=0.25, priority=0):
    """Copper zone/pour"""
    pt_str = ' '.join(f'(xy {x:.3f} {y:.3f})' for x,y in pts)
    nid = NET_IDS.get(net_name, 0)
    prio = f'(priority {priority}) ' if priority else ''
    return f'''  (zone (net {nid}) (net_name "{net_name}") (layer "{layer}") (uuid "{u()}")
    {prio}(connect_pads (clearance 0.3))
    (min_thickness {min_thk:.3f}) (filled_areas_thickness no)
    (fill yes (thermal_gap 0.5) (thermal_bridge_width 0.3))
    (polygon (pts {pt_str}))
  )'''

def edge(x1,y1,x2,y2):
    return (f'  (gr_line (start {x1:.3f} {y1:.3f}) (end {x2:.3f} {y2:.3f})'
            f' (layer "Edge.Cuts") (width 0.05) (uuid "{u()}"))')

def silk_text(txt, x, y, layer='F.SilkS', size=1.0):
    return (f'  (gr_text "{txt}" (at {x:.3f} {y:.3f}) (layer "{layer}")'
            f' (effects (font (size {size} {size}) (thickness 0.15))))')

# ─── Board outline ───────────────────────────────────────────────────────────
edges = [
    edge(0,0,W,0), edge(W,0,W,H), edge(W,H,0,H), edge(0,H,0,0)
]

# Corner mounting holes (M3, 3.2mm drill, 3mm from edges)
mholes = [
    fp("MountingHole:MountingHole_3.2mm_M3", f"H{i+1}", "MountingHole", mx, my)
    for i, (mx, my) in enumerate([(4,4),(W-4,4),(4,H-4),(W-4,H-4)])
]

# ─── Component placement ─────────────────────────────────────────────────────
# Board: 100x70mm, origin top-left
# Silk labels for regions
silks = [
    silk_text("ArtNet LED Controller v1.0", W/2, 1.5, 'F.SilkS', 1.5),
    silk_text("RP2354A + W5500 | 4x Serial LED | LiPo+USB-C", W/2, 4.0, 'F.SilkS', 0.8),
]

footprints = []

# ══ LEFT POWER COLUMN (x≈3..28) ═════════════════════════════════════════════
# Flow: USB-C → TP4056 ⇄ JST batt → D1 OR-gate → MT3608 boost → AMS1117 LDO

# USB-C (opening faces left edge)
footprints.append(fp(
    "Connector_USB:USB_C_Receptacle_GCT_USB4125-xx-x_6P_TopMnt_Horizontal",
    "J1","USB4125-GF-A", 5.0, 14, angle=90, lcsc='C165948'))

# TP4056 LiPo charger
footprints.append(fp(
    "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
    "U5","TP4056", 18, 14, lcsc='C16581'))

# Battery connector JST-PH-2 (cable exit points left off the edge)
footprints.append(fp(
    "Connector_JST:JST_PH_B2B-PH-K_1x02_P2.00mm_Vertical",
    "J3","VBAT JST-PH-2", 5.0, 28, angle=90, lcsc='C131337'))

# Schottky power-OR diode (VUSB + VBAT → VSYS)
footprints.append(fp("Diode_SMD:D_SOD-123","D1","SS14", 18, 28, lcsc='C2480'))

# MT3608 boost converter + inductor
footprints.append(fp(
    "Package_TO_SOT_SMD:SOT-23-6",
    "U6","MT3608", 12, 40, lcsc='C84817'))
footprints.append(fp(
    "Inductor_SMD:L_0805_2012Metric",
    "L1","22uH", 20, 40, lcsc='C1046'))

# AMS1117-3.3 LDO (5V → 3V3)
footprints.append(fp(
    "Package_TO_SOT_SMD:SOT-223-3_TabPin2",
    "U7","AMS1117-3.3", 18, 50, lcsc='C6186'))

# ══ CENTER MCU CLUSTER (x≈35..55) ═══════════════════════════════════════════
# RP2354A (center)
footprints.append(fp(
    "Package_DFN_QFN:QFN-60-1EP_7x7mm_P0.4mm_EP3.4x3.4mm",
    "U1","RP2354A", 46, 32, lcsc='C41378174'))

# 12MHz crystal — immediately below U1 XTAL pins
footprints.append(fp(
    "Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm",
    "Y1","12MHz", 46, 42, lcsc='C9002'))

# ══ RIGHT NETWORK CLUSTER (x≈62..92) ═════════════════════════════════════════
# W5500 Ethernet MAC/PHY
footprints.append(fp(
    "Package_QFP:LQFP-48_7x7mm_P0.5mm",
    "U3","W5500", 68, 32, lcsc='C32646'))

# 25MHz crystal — immediately below W5500
footprints.append(fp(
    "Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm",
    "Y2","25MHz", 68, 42, lcsc='C13738'))

# HR911105A RJ45 (right edge, horizontal)
footprints.append(fp(
    "Connector_RJ:RJ45_Hanrun_HR911105A_Horizontal",
    "J2","HR911105A", 90, 30, angle=270, lcsc='C12074'))

# ══ BOTTOM I/O ROW (y≈55..65) ════════════════════════════════════════════════
# SN74AHCT125 level shifter — between MCU and LED headers
footprints.append(fp(
    "Package_SO:SOIC-14_3.9x8.7mm_P1.27mm",
    "U4","SN74AHCT125", 50, 52, lcsc='C7484'))

# OLED header (bottom-left, near MCU I2C pins)
footprints.append(fp(
    "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical",
    "J9","OLED_SSD1306", 32, 62, lcsc='C124376'))

# SWD debug header
footprints.append(fp(
    "Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical",
    "J10","SWD_DEBUG", 40, 62, lcsc='C124375'))

# LED output connectors (bottom, right of U4)
for i in range(4):
    footprints.append(fp(
        "Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical",
        f"J{5+i}", f"LED_OUT_{i+1}", 60+i*7, 62, lcsc='C124375'))

# Buttons SW1/SW2 (user), SW3 (reset), SW4 (BOOTSEL)
for i,(bx,by) in enumerate([(8,60),(15,60),(86,60),(86,52)]):
    ref = f"SW{i+1}"
    footprints.append(fp(
        "Button_Switch_SMD:SW_Push_1P1T_NO_CK_KSC7xxJ",
        ref, "SW_Push", bx, by, lcsc='C318884', pads=simple_switch_pads()))

# ── Resistors (0402) - placed in clusters near their ICs ────────────────────
r_placements = [
    # (ref, value, x, y)  — positioned near their parent IC
    # Power section (left column)
    ('R1','750k',  16, 43),  # MT3608 FB top (above AMS1117 courtyard)
    ('R2','100k',  18, 43),  # MT3608 FB bot
    ('R3','2k',    24, 11),  # TP4056 PROG
    ('R4','5.1k',  10, 9),   # USB CC1
    ('R5','5.1k',  10, 19),  # USB CC2
    ('R7','10k',   24, 17),  # CHRG pullup
    ('R9','27',    25, 12),  # USB D+
    ('R10','27',   25, 16),  # USB D-
    # RP2354A (center)
    ('R6','330',   28, 18),  # power-indicator LED resistor (near D2)
    ('R8','10k',   40, 28),  # RUN pullup
    ('R23','33',   46, 25),  # RP2354A VREG_AVDD filter (above U1)
    ('R24','1k',   38, 40),  # BOOTSEL series resistor
    # SPI pullups between RP2354A and W5500
    ('R14','10k',  57, 28),  # SPI MISO pullup
    ('R15','10k',  57, 30),  # SPI CS pullup
    ('R16','10k',  57, 32),  # W5500 RST pullup
    # W5500 (right cluster)
    ('R11','12.4k',74, 26),  # W5500 EXRES0
    ('R12','12.4k',76, 26),  # W5500 RCLK
    ('R13','12.4k',78, 26),  # W5500 EXRES1
    ('R17','49.9', 82, 26),  # ETH CT1
    ('R18','49.9', 82, 28),  # ETH CT2
    # Bottom I/O
    ('R19','4.7k', 28, 58),  # I2C SCL pullup (OLED)
    ('R20','4.7k', 30, 58),  # I2C SDA pullup (OLED)
    ('R21','10k',  11, 56),  # BTN1 pullup
    ('R22','10k',  18, 56),  # BTN2 pullup
]
for ref,val,x,y in r_placements:
    footprints.append(fp("Resistor_SMD:R_0402_1005Metric", ref, val, x, y))

# ── Capacitors (0402 unless noted) ───────────────────────────────────────────
c_placements = [
    # (ref, val, x, y, fp_override)
    # Y1 12MHz crystal load caps — flanking Y1 at (46,42)
    ('C2','12pF',  43, 42, None),
    ('C3','12pF',  49, 42, None),
    # Y2 25MHz crystal load caps — flanking Y2 at (68,42)
    ('C5','18pF',  65, 42, None),
    ('C6','18pF',  71, 42, None),
    # Power section bulk/decoupling (left column)
    ('C31','10uF',  13, 9, 'Capacitor_SMD:C_0805_2012Metric'),  # VUSB bulk
    ('C32','100nF', 16, 9, None),
    ('C33','10uF',  12, 32, 'Capacitor_SMD:C_0805_2012Metric'),  # VBAT bulk
    ('C34','10uF',  24, 38, 'Capacitor_SMD:C_0805_2012Metric'),  # 5V bulk (MT3608 out)
    ('C35','100nF', 24, 42, None),
    ('C36','10uF',  25, 48, 'Capacitor_SMD:C_0805_2012Metric'),  # 3V3 bulk (AMS1117 out)
    ('C37','100nF', 25, 50, None),
    ('C38','100nF', 25, 52, None),
    # RP2354A decoupling corners at cheb=6 from U1 center (clears 4.1mm CrtYd)
    ('C39','100nF', 39, 26, None),
    ('C40','100nF', 52, 26, None),
    ('C41','100nF', 39, 38, None),
    ('C42','100nF', 52, 38, None),
    ('C43','100nF', 38, 30, None),
    ('C44','100nF', 38, 34, None),
    ('C45','100nF', 54, 34, None),
    ('C46','4.7uF', 54, 30, 'Capacitor_SMD:C_0402_1005Metric'),
    # RP2354A 1V1 core regulator caps
    ('C7','4.7uF',  46, 26, 'Capacitor_SMD:C_0402_1005Metric'),
    ('C8','100nF',  44, 26, None),   # VREG_AVDD
    ('C9','4.7uF',  48, 26, 'Capacitor_SMD:C_0402_1005Metric'),
    ('C10','4.7uF', 42, 26, 'Capacitor_SMD:C_0402_1005Metric'),
    # W5500 decoupling (LQFP-48 CrtYd extends 5.15mm) — caps at cheb≥6.5
    ('C4','100nF',  75, 32, None),   # W5_VDD
    ('C47','100nF', 63, 25, None),
    ('C48','100nF', 73, 25, None),
    ('C49','100nF', 63, 39, None),
    ('C50','100nF', 73, 39, None),
    ('C51','4.7uF', 75, 34, 'Capacitor_SMD:C_0402_1005Metric'),
    # Level shifter bypass (U4 at 50,52)
    ('C52','100nF', 55, 52, None),
]
for item in c_placements:
    ref,val,x,y = item[0],item[1],item[2],item[3]
    fp_lib = item[4] if item[4] else 'Capacitor_SMD:C_0402_1005Metric'
    footprints.append(fp(fp_lib, ref, val, x, y))

# ── RP2354A internal core regulator inductor (next to U1) ──────────────────
footprints.append(fp(
    "Inductor_SMD:L_0805_2012Metric",
    "L2","3.3uH", 55, 24, lcsc='C25923'))

# ── Power-on indicator LED ─────────────────────────────────────────────────
footprints.append(fp("LED_SMD:LED_0402_1005Metric","D2","LED_GREEN",28,20,lcsc='C72043'))

# ── Copper pours (4-layer stackup) ───────────────────────────────────────────
# F.Cu / B.Cu: signal only (no plane pour — freerouting needs the copper free)
# In1.Cu: solid VCC3V3 plane with a VCC5V island over the power-input column
# In2.Cu: solid GND plane (closer to B.Cu for short signal return paths)
vcc3v3_zone_i1 = zone("VCC3V3","In1.Cu",[(1,1),(W-1,1),(W-1,H-1),(1,H-1)])
vcc5v_zone_i1 = zone("VCC5V","In1.Cu", [(1,1),(30,1),(30,45),(1,45)], priority=2)
gnd_zone_i2 = zone("GND","In2.Cu",[(1,1),(W-1,1),(W-1,H-1),(1,H-1)])
power_pours = [vcc3v3_zone_i1, vcc5v_zone_i1, gnd_zone_i2]

# ─── Generate PCB ─────────────────────────────────────────────────────────────

STACKUP = '''  (setup
    (stackup
      (layer "F.SilkS" (type "Top Silk Screen"))
      (layer "F.Paste" (type "Top Solder Paste"))
      (layer "F.Mask" (type "Top Solder Mask") (thickness 0.01))
      (layer "F.Cu" (type "copper") (thickness 0.035))
      (layer "dielectric 1" (type "prepreg") (thickness 0.2104) (material "FR4") (epsilon_r 4.5) (loss_tangent 0.02))
      (layer "In1.Cu" (type "copper") (thickness 0.0152))
      (layer "dielectric 2" (type "core") (thickness 1.065) (material "FR4") (epsilon_r 4.5) (loss_tangent 0.02))
      (layer "In2.Cu" (type "copper") (thickness 0.0152))
      (layer "dielectric 3" (type "prepreg") (thickness 0.2104) (material "FR4") (epsilon_r 4.5) (loss_tangent 0.02))
      (layer "B.Cu" (type "copper") (thickness 0.035))
      (layer "B.Mask" (type "Bottom Solder Mask") (thickness 0.01))
      (layer "B.Paste" (type "Bottom Solder Paste"))
      (layer "B.SilkS" (type "Bottom Silk Screen"))
      (copper_finish "ENIG")
      (dielectric_constraints no)
    )
    (pad_to_mask_clearance 0.05)
    (solder_mask_min_width 0)
    (pad_to_paste_clearance 0)
    (pad_to_paste_clearance_ratio 0)
    (allow_soldermask_bridges_in_footprints no)
  )'''

pcb = ['(kicad_pcb (version 20230121) (generator pcbnew)',
       '  (general (thickness 1.6) (legacy_teardrops no))',
       '  (paper "A3")',
       f'  (title_block (title "ArtNet LED Controller")(rev "1.0")(company "Open Source"))',
       '',
       '  (layers',
       '    (0 "F.Cu" signal)',
       '    (1 "In1.Cu" power)',
       '    (2 "In2.Cu" power)',
       '    (31 "B.Cu" signal)',
       '    (32 "B.Adhes" user)',
       '    (33 "F.Adhes" user)',
       '    (34 "B.Paste" user)',
       '    (35 "F.Paste" user)',
       '    (36 "B.SilkS" user)',
       '    (37 "F.SilkS" user)',
       '    (38 "B.Mask" user)',
       '    (39 "F.Mask" user)',
       '    (40 "Dwgs.User" user)',
       '    (41 "Cmts.User" user)',
       '    (44 "Edge.Cuts" user)',
       '    (45 "Margin" user)',
       '    (46 "B.CrtYd" user)',
       '    (47 "F.CrtYd" user)',
       '    (48 "B.Fab" user)',
       '    (49 "F.Fab" user)',
       '  )',
       '',
       STACKUP,
       '',
       '  (net 0 "")',
       *[f'  (net {NET_IDS[n]} "{n}")' for n in _all_nets],
       '',
       ]

# Add board outline
pcb.extend(edges)

# Add mounting holes
pcb.extend(mholes)

# Silk labels
pcb.extend(silks)

# Add footprints
pcb.extend(footprints)

# Add copper pours
for _pour in power_pours:
    pcb.append(_pour)

# Power-plane stitching vias: DISABLED — let freerouting place its own vias.
# Pre-injected stitching vias clogged escape paths on the tight F.Cu area.
_plane_vias = []

# Closing
pcb.append(')')

out = '\n'.join(pcb)
print(f"  + {len(_plane_vias)} plane-stitching vias on power pads")
pcb_path = DIR / f"{PROJ}.kicad_pcb"
with open(pcb_path,'w') as f:
    f.write(out)
print(f"PCB written: {pcb_path} ({len(out):,} bytes)")
